// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmq0UE_SO1ciYJTkzkLBtBECV9cBiKIa0',
    appId: '1:915711779789:web:7e4f32861e374a21a61a84',
    messagingSenderId: '915711779789',
    projectId: 'smart-bin-app-uowd',
    authDomain: 'smart-bin-app-uowd.firebaseapp.com',
    storageBucket: 'smart-bin-app-uowd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZ86UM9Stun0BCe4Sf4q3mJta6v07dgc',
    appId: '1:915711779789:android:376749a6e6576caaa61a84',
    messagingSenderId: '915711779789',
    projectId: 'smart-bin-app-uowd',
    storageBucket: 'smart-bin-app-uowd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Jja-G2_40KcdWNGdfOSkxQ16A4CqSMw',
    appId: '1:915711779789:ios:ced175ce26e0e949a61a84',
    messagingSenderId: '915711779789',
    projectId: 'smart-bin-app-uowd',
    storageBucket: 'smart-bin-app-uowd.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Jja-G2_40KcdWNGdfOSkxQ16A4CqSMw',
    appId: '1:915711779789:ios:ced175ce26e0e949a61a84',
    messagingSenderId: '915711779789',
    projectId: 'smart-bin-app-uowd',
    storageBucket: 'smart-bin-app-uowd.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmq0UE_SO1ciYJTkzkLBtBECV9cBiKIa0',
    appId: '1:915711779789:web:9c3379b4851057a5a61a84',
    messagingSenderId: '915711779789',
    projectId: 'smart-bin-app-uowd',
    authDomain: 'smart-bin-app-uowd.firebaseapp.com',
    storageBucket: 'smart-bin-app-uowd.firebasestorage.app',
  );
}
